version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app

  db:
    container_name: "postgres"
    image: postgres:9.6
    volumes:
      - "/var/lib/postgresql/data"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sqlnode
      TZ: "GMT"
      PGTZ: "GMT"
